version: '3.8'

services:
  postgres:
    container_name: vs-system
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=vinicius
      - POSTGRES_PASSWORD=413380VSS
      - POSTGRES_DB=vs-system
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres